/**
 * IqraArena — ZK Proof Generator
 * --------------------------------
 * Generates a Groth16 reading proof using SnarkJS and submits it
 * to the zkVerify chain for on-chain verification.
 *
 * Flow:
 *   1. Collect reading session data (page content, duration, user secret)
 *   2. Hash the page content using Poseidon (ZK-friendly hash)
 *   3. Generate a Groth16 proof via SnarkJS
 *   4. Submit the proof to zkVerify using zkverify.js
 *   5. Receive attestation ID — used to unlock rewards on Base
 *
 * Dependencies:
 *   - snarkjs       : Groth16 proof generation
 *   - zkverify.js   : zkVerify chain submission
 *   - circomlibjs   : Poseidon hash (must match the circuit's hash function)
 */

const snarkjs = require("snarkjs");
const { buildPoseidon } = require("circomlibjs");
const { zkVerifySession, ZkVerifyEvents, Library, CurveType } = require("zkverifyjs");
const path = require("path");
const fs = require("fs");

// ── Constants ─────────────────────────────────────────────────────────────────

/**
 * Minimum reading time in seconds required per page.
 * This value is PUBLIC — it appears in the proof's public inputs
 * and is enforced by the on-chain reward contract.
 */
const MIN_READ_TIME_SECONDS = 30;

// Paths to compiled circuit artifacts (generated by circom + snarkjs setup)
const WASM_PATH = path.join(__dirname, "../build/reading_proof_js/reading_proof.wasm");
const ZKEY_PATH = path.join(__dirname, "../build/reading_proof_final.zkey");
const VK_PATH   = path.join(__dirname, "../build/verification_key.json");

// ── Helper: Poseidon hash ─────────────────────────────────────────────────────

/**
 * Computes a Poseidon hash of an array of BigInt values.
 * Poseidon is ZK-friendly — much cheaper to prove inside a circuit
 * than SHA256 or Keccak256.
 *
 * @param {BigInt[]} inputs - Array of field elements to hash
 * @returns {BigInt} - The Poseidon hash output
 */
async function poseidonHash(inputs) {
    const poseidon = await buildPoseidon();
    const hashResult = poseidon(inputs);
    return poseidon.F.toObject(hashResult);
}

// ── Helper: Derive user commitment ────────────────────────────────────────────

/**
 * Derives a public user commitment from the user's private secret.
 * This is stored on-chain as an anonymous user identifier.
 *
 * The user_secret never leaves the client. Only the commitment is public.
 *
 * @param {BigInt} userSecret - The user's private secret (stored locally)
 * @returns {BigInt} - The public user commitment = Poseidon(user_secret)
 */
async function deriveUserCommitment(userSecret) {
    return await poseidonHash([userSecret]);
}

// ── Core: Build circuit inputs ────────────────────────────────────────────────

/**
 * Prepares all inputs for the reading_proof circuit.
 *
 * @param {Object} session - Reading session data collected by the app
 * @param {string} session.pageContent     - Raw text content of the page
 * @param {number} session.readingDuration - Seconds spent on the page
 * @param {number} session.pageId          - Unique page identifier
 * @param {BigInt} session.userSecret      - User's private secret
 * @returns {Object} - { privateInputs, publicInputs } for the circuit
 */
async function buildCircuitInputs(session) {
    const { pageContent, readingDuration, pageId, userSecret } = session;

    // Derive user commitment (public, safe to expose on-chain)
    const userCommitment = await deriveUserCommitment(userSecret);

    // Hash the page content to keep it private while binding it to the proof
    // We encode the content as a UTF-8 byte array and fold into a single field element
    const contentBytes = Buffer.from(pageContent, "utf8");
    const contentAsBigInt = BigInt("0x" + contentBytes.toString("hex").slice(0, 62)); // fit in field
    const pageContentHash = await poseidonHash([contentAsBigInt, BigInt(pageId)]);

    // Current unix timestamp (seconds) — prevents replay attacks
    const sessionTimestamp = BigInt(Math.floor(Date.now() / 1000));

    return {
        // Private inputs — never leave the prover's machine
        privateInputs: {
            user_secret:       userSecret.toString(),
            page_content_hash: pageContentHash.toString(),
            reading_duration:  readingDuration.toString(),
        },
        // Public inputs — visible on-chain, safe to expose
        publicInputs: {
            user_commitment:   userCommitment.toString(),
            page_id:           pageId.toString(),
            session_timestamp: sessionTimestamp.toString(),
            min_read_time:     MIN_READ_TIME_SECONDS.toString(),
        },
    };
}

// ── Core: Generate Groth16 proof ──────────────────────────────────────────────

/**
 * Generates a Groth16 ZK proof for a completed reading session.
 *
 * @param {Object} session - Reading session data (see buildCircuitInputs)
 * @returns {Object} - { proof, publicSignals } ready for zkVerify submission
 */
async function generateReadingProof(session) {
    console.log(`[IqraArena] Generating ZK proof for page ${session.pageId}...`);

    // Build all circuit inputs
    const { privateInputs, publicInputs } = await buildCircuitInputs(session);

    // Combine private + public inputs as the circuit expects them
    const circuitInput = { ...privateInputs, ...publicInputs };

    // Generate the Groth16 proof using SnarkJS
    // This runs the circuit WASM to compute the witness, then generates the proof
    const { proof, publicSignals } = await snarkjs.groth16.fullProve(
        circuitInput,
        WASM_PATH,
        ZKEY_PATH
    );

    console.log(`[IqraArena] Proof generated successfully.`);
    console.log(`[IqraArena] Public signals: ${JSON.stringify(publicSignals)}`);

    return { proof, publicSignals };
}

// ── Core: Submit proof to zkVerify ────────────────────────────────────────────

/**
 * Submits a Groth16 proof to the zkVerify chain for on-chain verification.
 *
 * zkVerify reduces verification cost by 90%+ compared to verifying
 * directly on Base. After verification, an attestation is posted to Base
 * which triggers reward distribution in our smart contract.
 *
 * @param {Object} proof         - The Groth16 proof object from SnarkJS
 * @param {string[]} publicSignals - The public inputs/outputs of the proof
 * @returns {string} - The attestation ID from zkVerify
 */
async function submitToZkVerify(proof, publicSignals) {
    console.log(`[IqraArena] Submitting proof to zkVerify...`);

    // Load the verification key (registered once on-chain, reused for all proofs)
    const vk = JSON.parse(fs.readFileSync(VK_PATH, "utf8"));

    // Start a zkVerify session (uses env variable ZKVERIFY_SEED_PHRASE)
    const session = await zkVerifySession.start()
        .Testnet()
        .withAccount(process.env.ZKVERIFY_SEED_PHRASE);

    return new Promise((resolve, reject) => {
        // Submit the Groth16 proof for verification
        session.verify
            .groth16({
                // BN128 (BN254) curve — matches the Circom circuit's curve
                curve: CurveType.bn128,
                // Use pre-registered VK hash instead of re-registering each time
                // This saves gas on every submission
                vk: vk,
            })
            .execute(
                snarkjs.groth16.exportSolidityCallData(proof, publicSignals)
            )
            .on(ZkVerifyEvents.IncludedInBlock, (eventData) => {
                console.log(`[IqraArena] Proof included in zkVerify block:`, eventData);
            })
            .on(ZkVerifyEvents.Finalized, (eventData) => {
                console.log(`[IqraArena] Proof finalized on zkVerify.`);
                console.log(`[IqraArena] Attestation ID: ${eventData.attestationId}`);
                resolve(eventData.attestationId);
            })
            .on("error", (error) => {
                console.error(`[IqraArena] zkVerify submission error:`, error);
                reject(error);
            });
    });
}

// ── Main export: Full proof pipeline ─────────────────────────────────────────

/**
 * Full pipeline: generate proof → submit to zkVerify → return attestation.
 *
 * Called by the IqraArena backend when a user completes a reading session.
 * The returned attestationId is stored in our database and used by the
 * Base smart contract to verify and distribute reading rewards.
 *
 * @param {Object} session - Reading session data
 * @returns {string} - zkVerify attestation ID
 */
async function proveAndVerifyReading(session) {
    try {
        // Step 1: Generate the Groth16 proof
        const { proof, publicSignals } = await generateReadingProof(session);

        // Step 2: Submit to zkVerify and get attestation
        const attestationId = await submitToZkVerify(proof, publicSignals);

        return {
            success: true,
            attestationId,
            publicSignals,
        };
    } catch (error) {
        console.error(`[IqraArena] Proof pipeline failed:`, error);
        return {
            success: false,
            error: error.message,
        };
    }
}

module.exports = { proveAndVerifyReading, generateReadingProof, deriveUserCommitment };
